import { User, WebPost } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'PETER PARKER',
    handle: '@daily_bugle',
    university: 'Empire State University',
    aura: 1240,
    avatar: 'https://picsum.photos/seed/peter/200/200',
    interests: ['Photography', 'Journalism', 'Physics'],
    distance: '0.1mi',
    location: { x: 45, y: 30 },
  },
  {
    id: 'u2',
    name: 'GWEN STACY',
    handle: '@ghost_spider',
    university: 'Empire State University',
    aura: 890,
    avatar: 'https://picsum.photos/seed/gwen/200/200',
    interests: ['Music', 'Drums', 'Science'],
    distance: '0.3mi',
    location: { x: 70, y: 55 },
  },
  {
    id: 'u3',
    name: 'MILES MORALES',
    handle: '@brooklyn_spidey',
    university: 'Brooklyn Visions Academy',
    aura: 650,
    avatar: 'https://picsum.photos/seed/miles/200/200',
    interests: ['Art', 'Graffiti', 'Gaming'],
    distance: '0.8mi',
    location: { x: 25, y: 65 },
  },
];

export const MOCK_POSTS: WebPost[] = [
  {
    id: 'p1',
    userId: 'u1',
    userName: 'PETER PARKER',
    userHandle: '@daily_bugle',
    userUniversity: 'Empire State University',
    userAura: 1240,
    content: "Caught a perfect shot of the skyline tonight. Anyone near Chelsea want to grab a coffee and talk lens tech?",
    category: 'Coffee',
    distance: '0.2mi',
    timestamp: '12m',
    ttl: 48,
    joinedCount: 2,
    isExpiring: false,
  },
  {
    id: 'p2',
    userId: 'u3',
    userName: 'MILES MORALES',
    userHandle: '@brooklyn_spidey',
    userUniversity: 'Brooklyn Visions Academy',
    userAura: 650,
    content: "New mural project starting at the 4th St junction. Need some help with the high-climb sections if you have the gear.",
    category: 'Art',
    distance: '1.4mi',
    timestamp: '2h',
    ttl: 120,
    joinedCount: 5,
    isExpiring: false,
  },
  {
    id: 'p3',
    userId: 'u2',
    userName: 'GWEN STACY',
    userHandle: '@ghost_spider',
    userUniversity: 'Empire State University',
    userAura: 890,
    content: "Late night jam session at the basement bar. Looking for a bassist who doesn't mind a little noise.",
    category: 'Music',
    distance: '0.5mi',
    timestamp: '4m',
    ttl: 4,
    joinedCount: 1,
    isExpiring: true,
  },
];
